<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="FLE Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="Windows XP" host="QCCL-XP-SP3" qcserver="http://134.44.98.54:8080/qcbin" qcproject="DEFAULT.Demo_2"><DocLocation><![CDATA[[QualityCenter] Subject\Flight Reservation\Book Flight\Trip Type]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[Trip Type]]></DName>
<Res><![CDATA[Run_1-28_15-51-30]]></Res>
<TSet><![CDATA[Root\Mercury Tours Web Site\Functionality And UI\Mercury Tours Functionality]]></TSet>
<TInst><![CDATA[1]]></TInst>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="5" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Get URL [Departing And Arriving Locations]]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[File not found<BR>Line (6): &quot;ExecuteFile filePath&quot;. ]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:00]]></Time>
<TimeTick>1233159120</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" status="Failed" Source="Get URL [Departing And Arriving Locations]" SourceLine="5" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:00]]></Time>
<TimeTick>1233159120</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to http://134.44.98.54:8080/mtours/servlet/com.mercurytours.servlet.WelcomeServlet<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:00]]></Time>
<TimeTick>1233159120</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" nType="Navigate to http://134.44.98.54:8080/mtours/servlet/com.mercurytours.servlet.WelcomeServlet" Source="Get URL [Departing And Arriving Locations]" SourceLine="5" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Internet Explorer]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:17]]></Time>
<TimeTick>1233159137</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[&Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:17]]></Time>
<TimeTick>1233159137</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="23" status="Warning" Source="Get URL [Departing And Arriving Locations]" SourceLine="5" >
<Disp><![CDATA[&Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "&Yes" object's parent "Internet Explorer" (class Dialog). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:17]]></Time>
<TimeTick>1233159137</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Internet Explorer]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Visible = -1<br>Title = Internet Explorer<br>Native Class = #32770<br>]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:17]]></Time>
<TimeTick>1233159137</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="25" status="Warning" nType="Parent description" Source="Get URL [Departing And Arriving Locations]" SourceLine="5" >
<Disp><![CDATA[Internet Explorer]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="24" status="Warning" nType="Run Error" Source="Get URL [Departing And Arriving Locations]" SourceLine="5" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Optional step - Proceeding with replay]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:17]]></Time>
<TimeTick>1233159137</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="26" status="Information" nType="Error ignored" Source="Get URL [Departing And Arriving Locations]" SourceLine="5" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="22" status="Warning" Source="Get URL [Departing And Arriving Locations]" SourceLine="5" >
<Disp><![CDATA[Internet Explorer]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:17]]></Time>
<TimeTick>1233159137</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:17]]></Time>
<TimeTick>1233159137</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="30" Source="Get URL [Departing And Arriving Locations]" SourceLine="5" >
<Disp><![CDATA[Welcome: Mercury.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="29" Source="Get URL [Departing And Arriving Locations]" SourceLine="5" >
<Disp><![CDATA[Welcome: Mercury]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="11" status="Warning" Source="Get URL [Departing And Arriving Locations]" SourceLine="5" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="28.01.2009 - 18:12:00" eTime="28.01.2009 - 18:12:17" passed="0" failed="1" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" status="Failed" >
<Disp><![CDATA[Get URL [Departing And Arriving Locations] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T15">
<AName><![CDATA[Sign On [Departing And Arriving Locations]]]></AName>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:18]]></Time>
<TimeTick>1233159138</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:18]]></Time>
<TimeTick>1233159138</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[userName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["amit"]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:18]]></Time>
<TimeTick>1233159138</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="37" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[userName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["3ca1aa5e3043d80f9aae52"]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:18]]></Time>
<TimeTick>1233159138</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="40" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[password.SetSecure]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Sign-In.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:18]]></Time>
<TimeTick>1233159138</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="43" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[Sign-In.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="36" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[Welcome: Mercury]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Internet Explorer]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:29]]></Time>
<TimeTick>1233159149</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[&Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:29]]></Time>
<TimeTick>1233159149</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="54" status="Warning" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[&Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "&Yes" object's parent "Internet Explorer" (class Dialog). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:29]]></Time>
<TimeTick>1233159149</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Internet Explorer]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Visible = -1<br>Title = Internet Explorer<br>Native Class = #32770<br>]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:29]]></Time>
<TimeTick>1233159149</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="56" status="Warning" nType="Parent description" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[Internet Explorer]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="55" status="Warning" nType="Run Error" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Optional step - Proceeding with replay]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:29]]></Time>
<TimeTick>1233159149</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="57" status="Information" nType="Error ignored" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="53" status="Warning" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[Internet Explorer]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Security Alert]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:41]]></Time>
<TimeTick>1233159161</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[&Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:41]]></Time>
<TimeTick>1233159161</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="68" status="Warning" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[&Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "&Yes" object's parent "Security Alert" (class Dialog). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:41]]></Time>
<TimeTick>1233159161</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Security Alert]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Visible = -1<br>Title = Security Alert<br>Native Class = #32770<br>]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:41]]></Time>
<TimeTick>1233159161</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="70" status="Warning" nType="Parent description" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[Security Alert]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="69" status="Warning" nType="Run Error" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Optional step - Proceeding with replay]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:41]]></Time>
<TimeTick>1233159161</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="71" status="Information" nType="Error ignored" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="67" status="Warning" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[Security Alert]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Internet Explorer]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:47]]></Time>
<TimeTick>1233159167</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[&Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:47]]></Time>
<TimeTick>1233159167</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="82" status="Warning" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[&Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "&Yes" object's parent "Internet Explorer" (class Dialog). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:47]]></Time>
<TimeTick>1233159167</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Internet Explorer]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Visible = -1<br>Title = Internet Explorer<br>Native Class = #32770<br>]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:47]]></Time>
<TimeTick>1233159167</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="84" status="Warning" nType="Parent description" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[Internet Explorer]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="83" status="Warning" nType="Run Error" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Optional step - Proceeding with replay]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:47]]></Time>
<TimeTick>1233159167</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="85" status="Information" nType="Error ignored" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[&Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:52]]></Time>
<TimeTick>1233159172</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="95" status="Warning" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[&Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "&Yes" object's parent "Internet Explorer" (class Dialog). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:52]]></Time>
<TimeTick>1233159172</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Internet Explorer]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Visible = -1<br>Title = Internet Explorer<br>Native Class = #32770<br>]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:52]]></Time>
<TimeTick>1233159172</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="97" status="Warning" nType="Parent description" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[Internet Explorer]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="96" status="Warning" nType="Run Error" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Optional step - Proceeding with replay]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:52]]></Time>
<TimeTick>1233159172</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="98" status="Information" nType="Error ignored" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="81" status="Warning" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[Internet Explorer]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Find a Flight:]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:52]]></Time>
<TimeTick>1233159172</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Find a Flight:.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:52]]></Time>
<TimeTick>1233159172</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="102" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[Find a Flight:.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="101" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[Find a Flight:]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="35" status="Warning" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="28.01.2009 - 18:12:17" eTime="28.01.2009 - 18:12:52" passed="0" failed="0" warnings="8" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="32" status="Warning" >
<Disp><![CDATA[Sign On [Departing And Arriving Locations] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T42">
<AName><![CDATA[Trip Type]]></AName>
<AIter rID="T43" iterID="1" >
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Find a Flight:]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:53]]></Time>
<TimeTick>1233159173</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Find a Flight:]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:53]]></Time>
<TimeTick>1233159173</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[tripType.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["roundtrip"]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:53]]></Time>
<TimeTick>1233159173</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="110" Source="Trip Type" SourceLine="-1" >
<Disp><![CDATA[tripType.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[fromPort.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["London"]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:53]]></Time>
<TimeTick>1233159173</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="113" Source="Trip Type" SourceLine="-1" >
<Disp><![CDATA[fromPort.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[toPort.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Paris"]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:53]]></Time>
<TimeTick>1233159173</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="116" Source="Trip Type" SourceLine="-1" >
<Disp><![CDATA[toPort.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[findFlights.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[28.01.2009 - 18:12:53]]></Time>
<TimeTick>1233159173</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="119" Source="Trip Type" SourceLine="-1" >
<Disp><![CDATA[findFlights.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="109" Source="Trip Type" SourceLine="-1" >
<Disp><![CDATA[Find a Flight:]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Internet Explorer]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[28.01.2009 - 18:13:04]]></Time>
<TimeTick>1233159184</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[&Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[28.01.2009 - 18:13:04]]></Time>
<TimeTick>1233159184</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="130" status="Warning" Source="Trip Type" SourceLine="-1" >
<Disp><![CDATA[&Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "&Yes" object's parent "Internet Explorer" (class Dialog). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[28.01.2009 - 18:13:04]]></Time>
<TimeTick>1233159184</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Internet Explorer]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Visible = -1<br>Title = Internet Explorer<br>Native Class = #32770<br>]]></Details>
<Time><![CDATA[28.01.2009 - 18:13:04]]></Time>
<TimeTick>1233159184</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="132" status="Warning" nType="Parent description" Source="Trip Type" SourceLine="-1" >
<Disp><![CDATA[Internet Explorer]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="131" status="Warning" nType="Run Error" Source="Trip Type" SourceLine="-1" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Optional step - Proceeding with replay]]></Details>
<Time><![CDATA[28.01.2009 - 18:13:04]]></Time>
<TimeTick>1233159184</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="133" status="Information" nType="Error ignored" Source="Trip Type" SourceLine="-1" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[&Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[28.01.2009 - 18:13:10]]></Time>
<TimeTick>1233159190</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="143" status="Warning" Source="Trip Type" SourceLine="-1" >
<Disp><![CDATA[&Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "&Yes" object's parent "Internet Explorer" (class Dialog). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[28.01.2009 - 18:13:10]]></Time>
<TimeTick>1233159190</TimeTick>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Internet Explorer]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Visible = -1<br>Title = Internet Explorer<br>Native Class = #32770<br>]]></Details>
<Time><![CDATA[28.01.2009 - 18:13:10]]></Time>
<TimeTick>1233159190</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="145" status="Warning" nType="Parent description" Source="Trip Type" SourceLine="-1" >
<Disp><![CDATA[Internet Explorer]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="144" status="Warning" nType="Run Error" Source="Trip Type" SourceLine="-1" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Optional step - Proceeding with replay]]></Details>
<Time><![CDATA[28.01.2009 - 18:13:10]]></Time>
<TimeTick>1233159190</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="146" status="Information" nType="Error ignored" Source="Trip Type" SourceLine="-1" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[&Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[28.01.2009 - 18:13:16]]></Time>
<TimeTick>1233159196</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="156" status="Warning" Source="Trip Type" SourceLine="-1" >
<Disp><![CDATA[&Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "&Yes" object's parent "Internet Explorer" (class Dialog). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[28.01.2009 - 18:13:16]]></Time>
<TimeTick>1233159196</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Internet Explorer]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Visible = -1<br>Title = Internet Explorer<br>Native Class = #32770<br>]]></Details>
<Time><![CDATA[28.01.2009 - 18:13:16]]></Time>
<TimeTick>1233159196</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="158" status="Warning" nType="Parent description" Source="Trip Type" SourceLine="-1" >
<Disp><![CDATA[Internet Explorer]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="157" status="Warning" nType="Run Error" Source="Trip Type" SourceLine="-1" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Optional step - Proceeding with replay]]></Details>
<Time><![CDATA[28.01.2009 - 18:13:16]]></Time>
<TimeTick>1233159196</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="159" status="Information" nType="Error ignored" Source="Trip Type" SourceLine="-1" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="129" status="Warning" Source="Trip Type" SourceLine="-1" >
<Disp><![CDATA[Internet Explorer]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Select a Flight:]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[28.01.2009 - 18:13:16]]></Time>
<TimeTick>1233159196</TimeTick>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[Select a Flight:.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[28.01.2009 - 18:13:16]]></Time>