<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="FLE Standard Time">
<General productName="QuickTest Professional" productVer="11.00" os="Windows XP" host="AD-FT-XZHMUROV" qcserver="http://134.44.98.242/qcbin" qcproject="DO_NOT_TOUCH.ALM_Demo"><DocLocation><![CDATA[[QualityCenter] Subject\Flight Reservation\Flight Finder\Demo_ALM]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[Demo_ALM]]></DName>
<ConfName><![CDATA[Demo_ALM]]></ConfName>
<Res><![CDATA[Run_7-6_21-14-0]]></Res>
<DVer><![CDATA[1]]></DVer>
<TSet><![CDATA[Root\Mercury Tours Web Site\Demo_ALM]]></TSet>
<TInst><![CDATA[1]]></TInst>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="5" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Sing In]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[7/7/2010 - 4:13:39]]></Time>
<TimeTick>1278465219</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to http://newtours.demoaut.com/<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[7/7/2010 - 4:13:39]]></Time>
<TimeTick>1278465219</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" nType="Navigate to http://newtours.demoaut.com/" Source="Sing In" SourceLine="-1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "Welcome: Mercury Tours" (of class Browser). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[7/7/2010 - 4:14:00]]></Time>
<TimeTick>1278465240</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = Browser<br>CreationTime = 0<br>|Title = Welcome: Mercury Tours<br>openurl = http://www.google.com.ua<br>opentitle = Google<br>Opened By Testing Tool = 0<br>number of tabs = 1<br>Name = Welcome: Mercury Tours<br>Has Toolbar = -1<br>Has Status Bar = -1<br>Has Menu Bar = -1<br>]]></Details>
<Time><![CDATA[7/7/2010 - 4:14:00]]></Time>
<TimeTick>1278465240</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="14" status="Warning" nType="Description" Source="Sing In" SourceLine="-1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="13" status="Failed" nType="Run Error" Source="Sing In" SourceLine="-1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="10" status="Failed" Source="Sing In" SourceLine="-1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Welcome: Mercury Tours&quot; (of class Browser). Verify that this object's properties match an object currently displayed in your application.<BR>Line (3): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Navigate(URL)&quot;. ]]></Details>
<Time><![CDATA[7/7/2010 - 4:14:00]]></Time>
<TimeTick>1278465240</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" status="Failed" Source="Sing In" SourceLine="2" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[7/7/2010 - 4:15:04]]></Time>
<TimeTick>1278465304</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "Welcome: Mercury Tours" (of class Browser). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[7/7/2010 - 4:15:04]]></Time>
<TimeTick>1278465304</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = Browser<br>CreationTime = 0<br>|Title = Welcome: Mercury Tours<br>openurl = http://www.google.com.ua<br>opentitle = Google<br>Opened By Testing Tool = 0<br>number of tabs = 1<br>Name = Welcome: Mercury Tours<br>Has Toolbar = -1<br>Has Status Bar = -1<br>Has Menu Bar = -1<br>]]></Details>
<Time><![CDATA[7/7/2010 - 4:15:04]]></Time>
<TimeTick>1278465304</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="30" status="Warning" nType="Description" Source="Sing In" SourceLine="2" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="29" status="Failed" nType="Run Error" Source="Sing In" SourceLine="2" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="28" status="Failed" Source="Sing In" SourceLine="2" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Welcome: Mercury Tours&quot; (of class Browser). Verify that this object's properties match an object currently displayed in your application.<BR>Line (5): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Page(&quot;Welcome: Mercury Tours&quot;).Sync&quot;. ]]></Details>
<Time><![CDATA[7/7/2010 - 4:15:04]]></Time>
<TimeTick>1278465304</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="31" status="Failed" Source="Sing In" SourceLine="4" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[7/7/2010 - 4:16:51]]></Time>
<TimeTick>1278465411</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[7/7/2010 - 4:16:51]]></Time>
<TimeTick>1278465411</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[userName]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "userName" object's parent "Welcome: Mercury Tours" (class Browser). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[7/7/2010 - 4:16:51]]></Time>
<TimeTick>1278465411</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = Browser<br>CreationTime = 0<br>|Title = Welcome: Mercury Tours<br>openurl = http://www.google.com.ua<br>opentitle = Google<br>Opened By Testing Tool = 0<br>number of tabs = 1<br>Name = Welcome: Mercury Tours<br>Has Toolbar = -1<br>Has Status Bar = -1<br>Has Menu Bar = -1<br>]]></Details>
<Time><![CDATA[7/7/2010 - 4:16:51]]></Time>
<TimeTick>1278465411</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="64" status="Warning" nType="Parent description" Source="Sing In" SourceLine="4" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="63" status="Failed" nType="Run Error" Source="Sing In" SourceLine="4" >
<Disp><![CDATA[userName]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="62" status="Failed" Source="Sing In" SourceLine="4" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="61" status="Failed" Source="Sing In" SourceLine="4" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;userName&quot; object's parent &quot;Welcome: Mercury Tours&quot; (class Browser). Verify that parent properties match an object currently displayed in your application.<BR>Line (8): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Page(&quot;Welcome: Mercury Tours&quot;).WebEdit(&quot;userName&quot;).Set &quot;admin&quot;&quot;. ]]></Details>
<Time><![CDATA[7/7/2010 - 4:16:51]]></Time>
<TimeTick>1278465411</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="65" status="Failed" Source="Sing In" SourceLine="7" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[7/7/2010 - 4:18:38]]></Time>
<TimeTick>1278465518</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[7/7/2010 - 4:18:38]]></Time>
<TimeTick>1278465518</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[password]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "password" object's parent "Welcome: Mercury Tours" (class Browser). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[7/7/2010 - 4:18:38]]></Time>
<TimeTick>1278465518</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = Browser<br>CreationTime = 0<br>|Title = Welcome: Mercury Tours<br>openurl = http://www.google.com.ua<br>opentitle = Google<br>Opened By Testing Tool = 0<br>number of tabs = 1<br>Name = Welcome: Mercury Tours<br>Has Toolbar = -1<br>Has Status Bar = -1<br>Has Menu Bar = -1<br>]]></Details>
<Time><![CDATA[7/7/2010 - 4:18:38]]></Time>
<TimeTick>1278465518</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="98" status="Warning" nType="Parent description" Source="Sing In" SourceLine="7" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="97" status="Failed" nType="Run Error" Source="Sing In" SourceLine="7" >
<Disp><![CDATA[password]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="96" status="Failed" Source="Sing In" SourceLine="7" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="95" status="Failed" Source="Sing In" SourceLine="7" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;password&quot; object's parent &quot;Welcome: Mercury Tours&quot; (class Browser). Verify that parent properties match an object currently displayed in your application.<BR>Line (9): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Page(&quot;Welcome: Mercury Tours&quot;).WebEdit(&quot;password&quot;).Set &quot;admin&quot;&quot;. ]]></Details>
<Time><![CDATA[7/7/2010 - 4:18:38]]></Time>
<TimeTick>1278465518</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="99" status="Failed" Source="Sing In" SourceLine="8" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[7/7/2010 - 4:20:18]]></Time>
<TimeTick>1278465618</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[7/7/2010 - 4:20:18]]></Time>
<TimeTick>1278465618</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Sign-In]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "Sign-In" object's parent "Welcome: Mercury Tours" (class Page). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[7/7/2010 - 4:20:18]]></Time>
<TimeTick>1278465618</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = Page<br>|Url = http://newtours.demoaut.com<br>Title = Welcome: Mercury Tours<br>]]></Details>
<Time><![CDATA[7/7/2010 - 4:20:18]]></Time>
<TimeTick>1278465618</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="125" status="Warning" nType="Parent description" Source="Sing In" SourceLine="8" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="124" status="Failed" nType="Run Error" Source="Sing In" SourceLine="8" >
<Disp><![CDATA[Sign-In]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="123" status="Failed" Source="Sing In" SourceLine="8" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="122" status="Failed" Source="Sing In" SourceLine="8" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the &quot;Sign-In&quot; object's parent &quot;Welcome: Mercury Tours&quot; (class Page). Verify that parent properties match an object currently displayed in your application.<BR>Line (10): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Page(&quot;Welcome: Mercury Tours&quot;).Image(&quot;Sign-In&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[7/7/2010 - 4:20:18]]></Time>
<TimeTick>1278465618</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="126" status="Failed" Source="Sing In" SourceLine="9" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="7/7/2010 - 4:13:39" eTime="7/7/2010 - 4:20:18" passed="0" failed="10" warnings="5" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" status="Failed" >
<Disp><![CDATA[Sing In Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T29">
<AName><![CDATA[Data_Alm]]></AName>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[7/7/2010 - 4:20:19]]></Time>
<TimeTick>1278465619</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Find a Flight: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[7/7/2010 - 4:20:19]]></Time>
<TimeTick>1278465619</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Find a Flight: Mercury.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[7/7/2010 - 4:20:19]]></Time>
<TimeTick>1278465619</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="133" Source="Data_Alm" SourceLine="-1" >
<Disp><![CDATA[Find a Flight: Mercury.Sync]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[fromPort]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "fromPort" (of class WebList). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[7/7/2010 - 4:20:40]]></Time>
<TimeTick>1278465640</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[fromPort]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WebList<br>Html Tag = SELECT<br>_xpath = //TR[normalize-space()="Departing From: AcapulcoFrankfurtLondonNew YorkParisPortlandSan FranciscoSeattleSydneyZurich"]/TD[2]/SELECT[1]<br>|Visible Items = 0<br>Visible = -1<br>Name = fromPort<br>Items Count = 10<br>Html Id = <br>default value = <br>DHTML Class = <br>]]></Details>
<Time><![CDATA[7/7/2010 - 4:20:40]]></Time>
<TimeTick>1278465640</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="179" status="Warning" nType="Description" Source="Data_Alm" SourceLine="-1" >
<Disp><![CDATA[fromPort]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="178" status="Failed" nType="Run Error" Source="Data_Alm" SourceLine="-1" >
<Disp><![CDATA[fromPort]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="132" status="Failed" Source="Data_Alm" SourceLine="-1" >
<Disp><![CDATA[Find a Flight: Mercury]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="131" status="Failed" Source="Data_Alm" SourceLine="-1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;fromPort&quot; (of class WebList). Verify that this object's properties match an object currently displayed in your application.<BR>Line (8): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Page(&quot;Find a Flight: Mercury&quot;).WebList(&quot;fromPort&quot;).Select DataTable(&quot;p_from_port&quot;, dtGlobalSheet)&quot;. ]]></Details>
<Time><![CDATA[7/7/2010 - 4:20:40]]></Time>
<TimeTick>1278465640</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="180" status="Failed" Source="Data_Alm" SourceLine="7" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[7/7/2010 - 4:21:00]]></Time>
<TimeTick>1278465660</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Find a Flight: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[7/7/2010 - 4:21:00]]></Time>
<TimeTick>1278465660</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[toPort]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "toPort" (of class WebList). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[7/7/2010 - 4:21:00]]></Time>
<TimeTick>1278465660</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[toPort]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WebList<br>Html Tag = SELECT<br>_xpath = //TR[normalize-space()="Arriving In: AcapulcoFrankfurtLondonNew YorkParisPortlandSan FranciscoSeattleSydneyZurich"]/TD[2]/SELECT[1]<br>|Visible Items = 0<br>Visible = -1<br>Name = toPort<br>Items Count = 10<br>Html Id = <br>default value = <br>DHTML Class = <br>]]></Details>
<Time><![CDATA[7/7/2010 - 4:21:00]]></Time>
<TimeTick>1278465660</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="228" status="Warning" nType="Description" Source="Data_Alm" SourceLine="7" >
<Disp><![CDATA[toPort]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="227" status="Failed" nType="Run Error" Source="Data_Alm" SourceLine="7" >
<Disp><![CDATA[toPort]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="226" status="Failed" Source="Data_Alm" SourceLine="7" >
<Disp><![CDATA[Find a Flight: Mercury]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="225" status="Failed" Source="Data_Alm" SourceLine="7" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;toPort&quot; (of class WebList). Verify that this object's properties match an object currently displayed in your application.<BR>Line (9): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Page(&quot;Find a Flight: Mercury&quot;).WebList(&quot;toPort&quot;).Select DataTable(&quot;p_to_port&quot;, dtGlobalSheet)&quot;. ]]></Details>
<Time><![CDATA[7/7/2010 - 4:21:00]]></Time>
<TimeTick>1278465660</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="229" status="Failed" Source="Data_Alm" SourceLine="8" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[7/7/2010 - 4:21:21]]></Time>
<TimeTick>1278465681</TimeTick>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Find a Flight: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[7/7/2010 - 4:21:21]]></Time>
<TimeTick>1278465681</TimeTick>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[airline]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "airline" (of class WebList). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[7/7/2010 - 4:21:21]]></Time>
<TimeTick>1278465681</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[airline]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WebList<br>Html Tag = SELECT<br>_xpath = //TR/TD/SELECT[normalize-space()="No Preference Blue Skies Airlines Unified Airlines Pangea Airlines"]<br>|Visible Items = 0<br>Visible = -1<br>Name = airline<br>Items Count = 4<br>Html Id = <br>default value = <br>DHTML Class = <br>]]></Details>
<Time><![CDATA[7/7/2010 - 4:21:21]]></Time>
<TimeTick>1278465681</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="277" status="Warning" nType="Description" Source="Data_Alm" SourceLine="8" >
<Disp><![CDATA[airline]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="276" status="Failed" nType="Run Error" Source="Data_Alm" SourceLine="8" >
<Disp><![CDATA[airline]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="275" status="Failed" Source="Data_Alm" SourceLine="8" >
<Disp><![CDATA[Find a Flight: Mercury]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="274" status="Failed" Source="Data_Alm" SourceLine="8" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;airline&quot; (of class WebList). Verify that this object's properties match an object currently displayed in your application.<BR>Line (10): &quot;Browser(&quot;Welcome: Mercury Tours&quot;).Page(&quot;Find a Flight: Mercury&quot;).WebList(&quot;airline&quot;).Select DataTable(&quot;p_airline&quot;, dtGlobalSheet)&quot;. ]]></Details>
<Time><![CDATA[7/7/2010 - 4:21:21]]></Time>
<TimeTick>1278465681</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="278" status="Failed" Source="Data_Alm" SourceLine="9" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[7/7/2010 - 4:21:21]]></Time>
<TimeTick>1278465681</TimeTick>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Find a Flight: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[7/7/2010 - 4:21:21]]></Time>
<TimeTick>1278465681</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Find a Flight: Mercury.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[7/7/2010 - 4:21:21]]></Time>
<TimeTick>1278465681</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="283" Source="Data_Alm" SourceLine="9" >
<Disp><![CDATA[Find a Flight: Mercury.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="282" Source="Data_Alm" SourceLine="9" >
<Disp><![CDATA[Find a Flight: Mercury]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours.Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[7/7/2010 - 4:21:21]]></Time>
<TimeTick>1278465681</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="284" Source="Data_Alm" SourceLine="9" >
<Disp><![CDATA[Welcome: Mercury Tours.Close]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="281" Source="Data_Alm" SourceLine="9" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="7/7/2010 - 4:20:18" eTime="7/7/2010 - 4:21:21" passed="0" failed="6" warnings="3" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="128" status="Failed" >
<Disp><![CDATA[Data_Alm Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="7" status="Failed" >
<Disp><![CDATA[Demo_ALM Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T50" iterID="2" >
<Action rID="T51">
<AName><![CDATA[Sing In]]></AName>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[7/7/2010 - 4:21:26]]></Time>
<TimeTick>1278465686</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to http://newtours.demoaut.com/<br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[7/7/2010 - 4:21:26]]></Time>
<TimeTick>1278465686</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="291" nType="Navigate to http://newtours.demoaut.com/" Source="Sing In" SourceLine="-1" >
<Disp><![CDATA[Welcome: Mercury Tours]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury Tours]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "Welcome: Mercury Tours" (of class Browser). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[7/7/2010 - 4:21:47]]></Time>
<TimeTick>1278465707</TimeTick>
<Step rID="T55">