<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="FLE Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="Windows XP" host="QCCL-XP-SP3" qcserver="http://134.44.98.54:8080/qcbin" qcproject="DEFAULT.Demo_2"><DocLocation><![CDATA[[QualityCenter] Subject\Flight Reservation\Book Flight\Number Of Passengers]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[Number Of Passengers]]></DName>
<Res><![CDATA[Run_1-28_15-51-30]]></Res>
<TSet><![CDATA[Root\Mercury Tours Web Site\Functionality And UI\Mercury Tours Functionality]]></TSet>
<TInst><![CDATA[1]]></TInst>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="5" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Get URL [Departing And Arriving Locations]]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[File not found<BR>Line (6): &quot;ExecuteFile filePath&quot;. ]]></Details>
<Time><![CDATA[28.01.2009 - 17:57:26]]></Time>
<TimeTick>1233158246</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" status="Failed" Source="Get URL [Departing And Arriving Locations]" SourceLine="5" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Type mismatch: 'Get_URL'<BR>Line (7): &quot;URL = Get_URL()&quot;. ]]></Details>
<Time><![CDATA[28.01.2009 - 17:57:26]]></Time>
<TimeTick>1233158246</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Failed" Source="Get URL [Departing And Arriving Locations]" SourceLine="6" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[28.01.2009 - 17:57:26]]></Time>
<TimeTick>1233158246</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Navigate to <br>Target Frame: _top<br>Post Data: <br>HTTP Headers: ]]></Details>
<Time><![CDATA[28.01.2009 - 17:57:26]]></Time>
<TimeTick>1233158246</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" nType="Navigate to " Source="Get URL [Departing And Arriving Locations]" SourceLine="6" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Internet Explorer]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[28.01.2009 - 17:57:43]]></Time>
<TimeTick>1233158263</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[&Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[28.01.2009 - 17:57:43]]></Time>
<TimeTick>1233158263</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="24" status="Warning" Source="Get URL [Departing And Arriving Locations]" SourceLine="6" >
<Disp><![CDATA[&Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "&Yes" object's parent "Internet Explorer" (class Dialog). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[28.01.2009 - 17:57:43]]></Time>
<TimeTick>1233158263</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Internet Explorer]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Visible = -1<br>Title = Internet Explorer<br>Native Class = #32770<br>]]></Details>
<Time><![CDATA[28.01.2009 - 17:57:43]]></Time>
<TimeTick>1233158263</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="26" status="Warning" nType="Parent description" Source="Get URL [Departing And Arriving Locations]" SourceLine="6" >
<Disp><![CDATA[Internet Explorer]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="25" status="Warning" nType="Run Error" Source="Get URL [Departing And Arriving Locations]" SourceLine="6" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Optional step - Proceeding with replay]]></Details>
<Time><![CDATA[28.01.2009 - 17:57:43]]></Time>
<TimeTick>1233158263</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="27" status="Information" nType="Error ignored" Source="Get URL [Departing And Arriving Locations]" SourceLine="6" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="23" status="Warning" Source="Get URL [Departing And Arriving Locations]" SourceLine="6" >
<Disp><![CDATA[Internet Explorer]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[28.01.2009 - 17:57:43]]></Time>
<TimeTick>1233158263</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[28.01.2009 - 17:57:43]]></Time>
<TimeTick>1233158263</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="31" Source="Get URL [Departing And Arriving Locations]" SourceLine="6" >
<Disp><![CDATA[Welcome: Mercury.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="30" Source="Get URL [Departing And Arriving Locations]" SourceLine="6" >
<Disp><![CDATA[Welcome: Mercury]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="12" status="Warning" Source="Get URL [Departing And Arriving Locations]" SourceLine="6" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="28.01.2009 - 17:57:26" eTime="28.01.2009 - 17:57:43" passed="0" failed="2" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" status="Failed" >
<Disp><![CDATA[Get URL [Departing And Arriving Locations] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T16">
<AName><![CDATA[Sign On [Departing And Arriving Locations]]]></AName>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[28.01.2009 - 17:57:49]]></Time>
<TimeTick>1233158269</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[28.01.2009 - 17:57:49]]></Time>
<TimeTick>1233158269</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[userName]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "userName" (of class WebEdit). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[28.01.2009 - 17:57:49]]></Time>
<TimeTick>1233158269</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[userName]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Visible = 1<br>Type = text<br>rows = 0<br>Name = userName<br>Mercury Class = WebEdit<br>Max Length = 2147483647<br>Html Tag = INPUT<br>Html Id = <br>default value = <br>cols = 10<br>DHTML Class = <br>]]></Details>
<Time><![CDATA[28.01.2009 - 17:57:49]]></Time>
<TimeTick>1233158269</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="51" status="Warning" nType="Description" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[userName]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="50" status="Failed" nType="Run Error" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[userName]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="49" status="Failed" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[Welcome: Mercury]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="48" status="Failed" Source="Sign On [Departing And Arriving Locations]" SourceLine="-1" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;userName&quot; (of class WebEdit). Verify that this object's properties match an object currently displayed in your application.<BR>Line (2): &quot;Browser(&quot;Browser&quot;).Page(&quot;Welcome: Mercury&quot;).WebEdit(&quot;userName&quot;).Set DataTable(&quot;Username&quot;, dtLocalSheet)&quot;. ]]></Details>
<Time><![CDATA[28.01.2009 - 17:57:49]]></Time>
<TimeTick>1233158269</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="52" status="Failed" Source="Sign On [Departing And Arriving Locations]" SourceLine="1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[28.01.2009 - 17:57:54]]></Time>
<TimeTick>1233158274</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[28.01.2009 - 17:57:54]]></Time>
<TimeTick>1233158274</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[password]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "password" (of class WebEdit). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[28.01.2009 - 17:57:54]]></Time>
<TimeTick>1233158274</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[password]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Visible = 1<br>Type = password<br>rows = 0<br>Name = password<br>Mercury Class = WebEdit<br>Max Length = 2147483647<br>Html Tag = INPUT<br>Html Id = <br>default value = <br>cols = 10<br>DHTML Class = <br>]]></Details>
<Time><![CDATA[28.01.2009 - 17:57:54]]></Time>
<TimeTick>1233158274</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="70" status="Warning" nType="Description" Source="Sign On [Departing And Arriving Locations]" SourceLine="1" >
<Disp><![CDATA[password]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="10" nRep="69" status="Failed" nType="Run Error" Source="Sign On [Departing And Arriving Locations]" SourceLine="1" >
<Disp><![CDATA[password]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="68" status="Failed" Source="Sign On [Departing And Arriving Locations]" SourceLine="1" >
<Disp><![CDATA[Welcome: Mercury]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="67" status="Failed" Source="Sign On [Departing And Arriving Locations]" SourceLine="1" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;password&quot; (of class WebEdit). Verify that this object's properties match an object currently displayed in your application.<BR>Line (3): &quot;Browser(&quot;Browser&quot;).Page(&quot;Welcome: Mercury&quot;).WebEdit(&quot;password&quot;).SetSecure DataTable(&quot;Password&quot;, dtLocalSheet)&quot;. ]]></Details>
<Time><![CDATA[28.01.2009 - 17:57:54]]></Time>
<TimeTick>1233158274</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="71" status="Failed" Source="Sign On [Departing And Arriving Locations]" SourceLine="2" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:00]]></Time>
<TimeTick>1233158280</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Welcome: Mercury]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:00]]></Time>
<TimeTick>1233158280</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Sign-In]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "Sign-In" (of class Image). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:00]]></Time>
<TimeTick>1233158280</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Sign-In]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Width = 58<br>Visible = 1<br>Name = login<br>Mercury Class = Image<br>Image Type = Image Button<br>Html Tag = INPUT<br>Html Id = <br>Height = 17<br>file name = btn_signin.gif<br>DHTML Class = <br>Alt = Sign-In<br>]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:00]]></Time>
<TimeTick>1233158280</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="89" status="Warning" nType="Description" Source="Sign On [Departing And Arriving Locations]" SourceLine="2" >
<Disp><![CDATA[Sign-In]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="11" nRep="88" status="Failed" nType="Run Error" Source="Sign On [Departing And Arriving Locations]" SourceLine="2" >
<Disp><![CDATA[Sign-In]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="87" status="Failed" Source="Sign On [Departing And Arriving Locations]" SourceLine="2" >
<Disp><![CDATA[Welcome: Mercury]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="86" status="Failed" Source="Sign On [Departing And Arriving Locations]" SourceLine="2" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Sign-In&quot; (of class Image). Verify that this object's properties match an object currently displayed in your application.<BR>Line (4): &quot;Browser(&quot;Browser&quot;).Page(&quot;Welcome: Mercury&quot;).Image(&quot;Sign-In&quot;).Click 14, 11&quot;. ]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:00]]></Time>
<TimeTick>1233158280</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="90" status="Failed" Source="Sign On [Departing And Arriving Locations]" SourceLine="3" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:11]]></Time>
<TimeTick>1233158291</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Internet Explorer]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:11]]></Time>
<TimeTick>1233158291</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[&Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:11]]></Time>
<TimeTick>1233158291</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="102" status="Warning" Source="Sign On [Departing And Arriving Locations]" SourceLine="3" >
<Disp><![CDATA[&Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "&Yes" object's parent "Internet Explorer" (class Dialog). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:11]]></Time>
<TimeTick>1233158291</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Internet Explorer]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Visible = -1<br>Title = Internet Explorer<br>Native Class = #32770<br>]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:11]]></Time>
<TimeTick>1233158291</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="104" status="Warning" nType="Parent description" Source="Sign On [Departing And Arriving Locations]" SourceLine="3" >
<Disp><![CDATA[Internet Explorer]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="103" status="Warning" nType="Run Error" Source="Sign On [Departing And Arriving Locations]" SourceLine="3" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Optional step - Proceeding with replay]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:11]]></Time>
<TimeTick>1233158291</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="105" status="Information" nType="Error ignored" Source="Sign On [Departing And Arriving Locations]" SourceLine="3" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="101" status="Warning" Source="Sign On [Departing And Arriving Locations]" SourceLine="3" >
<Disp><![CDATA[Internet Explorer]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Security Alert]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:23]]></Time>
<TimeTick>1233158303</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[&Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:23]]></Time>
<TimeTick>1233158303</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="116" status="Warning" Source="Sign On [Departing And Arriving Locations]" SourceLine="3" >
<Disp><![CDATA[&Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "&Yes" object's parent "Security Alert" (class Dialog). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:23]]></Time>
<TimeTick>1233158303</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Security Alert]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Visible = -1<br>Title = Security Alert<br>Native Class = #32770<br>]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:23]]></Time>
<TimeTick>1233158303</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="118" status="Warning" nType="Parent description" Source="Sign On [Departing And Arriving Locations]" SourceLine="3" >
<Disp><![CDATA[Security Alert]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="117" status="Warning" nType="Run Error" Source="Sign On [Departing And Arriving Locations]" SourceLine="3" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Optional step - Proceeding with replay]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:23]]></Time>
<TimeTick>1233158303</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="119" status="Information" nType="Error ignored" Source="Sign On [Departing And Arriving Locations]" SourceLine="3" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="115" status="Warning" Source="Sign On [Departing And Arriving Locations]" SourceLine="3" >
<Disp><![CDATA[Security Alert]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Internet Explorer]]></Obj>
<Details plainTxt="False" ><![CDATA[Dialog]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:29]]></Time>
<TimeTick>1233158309</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[&Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:29]]></Time>
<TimeTick>1233158309</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="130" status="Warning" Source="Sign On [Departing And Arriving Locations]" SourceLine="3" >
<Disp><![CDATA[&Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "&Yes" object's parent "Internet Explorer" (class Dialog). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:29]]></Time>
<TimeTick>1233158309</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Internet Explorer]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Visible = -1<br>Title = Internet Explorer<br>Native Class = #32770<br>]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:29]]></Time>
<TimeTick>1233158309</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="132" status="Warning" nType="Parent description" Source="Sign On [Departing And Arriving Locations]" SourceLine="3" >
<Disp><![CDATA[Internet Explorer]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="131" status="Warning" nType="Run Error" Source="Sign On [Departing And Arriving Locations]" SourceLine="3" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Optional step - Proceeding with replay]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:29]]></Time>
<TimeTick>1233158309</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="133" status="Information" nType="Error ignored" Source="Sign On [Departing And Arriving Locations]" SourceLine="3" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[&Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:35]]></Time>
<TimeTick>1233158315</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="143" status="Warning" Source="Sign On [Departing And Arriving Locations]" SourceLine="3" >
<Disp><![CDATA[&Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "&Yes" object's parent "Internet Explorer" (class Dialog). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:35]]></Time>
<TimeTick>1233158315</TimeTick>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Internet Explorer]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Visible = -1<br>Title = Internet Explorer<br>Native Class = #32770<br>]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:35]]></Time>
<TimeTick>1233158315</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="145" status="Warning" nType="Parent description" Source="Sign On [Departing And Arriving Locations]" SourceLine="3" >
<Disp><![CDATA[Internet Explorer]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="144" status="Warning" nType="Run Error" Source="Sign On [Departing And Arriving Locations]" SourceLine="3" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[&Yes]]></Obj>
<Details plainTxt="False" ><![CDATA[Optional step - Proceeding with replay]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:35]]></Time>
<TimeTick>1233158315</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="146" status="Information" nType="Error ignored" Source="Sign On [Departing And Arriving Locations]" SourceLine="3" >
<Disp><![CDATA[&Yes]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="129" status="Warning" Source="Sign On [Departing And Arriving Locations]" SourceLine="3" >
<Disp><![CDATA[Internet Explorer]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Find a Flight:]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:35]]></Time>
<TimeTick>1233158315</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Find a Flight:.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:35]]></Time>
<TimeTick>1233158315</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="150" Source="Sign On [Departing And Arriving Locations]" SourceLine="3" >
<Disp><![CDATA[Find a Flight:.Sync]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="9" nRep="149" Source="Sign On [Departing And Arriving Locations]" SourceLine="3" >
<Disp><![CDATA[Find a Flight:]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="100" status="Warning" Source="Sign On [Departing And Arriving Locations]" SourceLine="3" >
<Disp><![CDATA[Browser]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="28.01.2009 - 17:57:43" eTime="28.01.2009 - 17:58:35" passed="0" failed="6" warnings="11" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="33" status="Failed" >
<Disp><![CDATA[Sign On [Departing And Arriving Locations] Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T54">
<AName><![CDATA[Number Of Passengers]]></AName>
<AIter rID="T55" iterID="1" >
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Find a Flight:]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:40]]></Time>
<TimeTick>1233158320</TimeTick>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Find a Flight:]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:40]]></Time>
<TimeTick>1233158320</TimeTick>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[tripType]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object "tripType" (of class WebRadioGroup). Verify that this object's properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:40]]></Time>
<TimeTick>1233158320</TimeTick>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[tripType]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Visible = 1<br>Name = tripType<br>Mercury Class = WebRadioGroup<br>Items Count = 2<br>Html Tag = INPUT<br>Html Id = <br>DHTML Class = <br>]]></Details>
<Time><![CDATA[28.01.2009 - 17:58:40]]></Time>
<TimeTick>1233158320</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="171" status="Warning" nType="Description" Source="Number Of Passengers" SourceLine="-1" >